/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TugasPrak;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author USER
 */
public class GUI_Pembayaran extends javax.swing.JFrame {
public GUI_Pembayaran() {
        initComponents();
        DefaultTableModel dataModel = (DefaultTableModel) tabel_data_pembayaran.getModel();
        int rowCount = dataModel.getRowCount();
        while (rowCount > 0){
            dataModel.removeRow(rowCount - 1);
            rowCount = dataModel.getRowCount();
        }
}
    /**
     * Creates new form GUI_Pembayaran
     */
public void clear() {
    txthargabarang.setText("");
    txtkp.setText("");
    txtpembayaran.setText("");
 }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpembayaran = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        memopembayaran = new javax.swing.JTextArea();
        btnbayar = new javax.swing.JToggleButton();
        btnclose = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        txthargabarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtkp = new javax.swing.JTextField();
        cmb_langganan = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_data_pembayaran = new javax.swing.JTable();
        btn_battal = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PEMBAYARAN");

        jLabel2.setText("PEMBAYARAN");

        memopembayaran.setColumns(20);
        memopembayaran.setRows(5);
        jScrollPane1.setViewportView(memopembayaran);

        btnbayar.setText("BAYAR");
        btnbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbayarActionPerformed(evt);
            }
        });

        btnclose.setText("CLOSE");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        jLabel3.setText("HARGA BARANG");

        jLabel4.setText("KODE PEMBAYARAN");

        Pembayaran pembayaran = new Pembayaran();
        pembayaran.generateKodePembayaran();
        String kp = pembayaran.getKodepembayaran();        
        txtkp.setText(kp);
        txtkp.setEditable(false);
        txtkp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkpActionPerformed(evt);
            }
        });

        cmb_langganan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak Langganan", "Langganan", "Member", " " }));
        cmb_langganan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_langgananActionPerformed(evt);
            }
        });

        tabel_data_pembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PEMBAYARAN", "HARGA BARANG", "KODE PEMBAYARAN", "LANGGANAN"
            }
        ));
        jScrollPane2.setViewportView(tabel_data_pembayaran);

        btn_battal.setText("BATAL");
        btn_battal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_battalActionPerformed(evt);
            }
        });

        btn_hapus.setText("HAPUS");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel1)
                        .addGap(0, 306, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txthargabarang, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtkp)
                            .addComponent(txtpembayaran))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb_langganan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btn_battal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnbayar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnclose, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                    .addComponent(btn_hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_langganan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txthargabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_battal)
                    .addComponent(btn_hapus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnbayar)
                    .addComponent(btnclose))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbayarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Data anda Ditambahkan Ke tabel");
        DefaultTableModel dataModel = (DefaultTableModel)
        tabel_data_pembayaran.getModel();
        List list = new ArrayList<>();
        tabel_data_pembayaran.setAutoCreateColumnsFromModel(true);
        Pembayaran bayar = new Pembayaran();
        bayar.dataHarga(Integer.parseInt(txthargabarang.getText()));
        bayar.dataPembayaran(Integer.parseInt(txtpembayaran.getText()));
        bayar.setKodepembayaran(txtkp.getText());
        bayar.dataPelanggan((String) cmb_langganan.getSelectedItem());
        list.add(bayar.cetakHarga());
        list.add(bayar.cetakPembayaran());
        list.add(bayar.cetakKodePembayaran());
        list.add(bayar.cetakPelanggan());
        dataModel.addRow(list.toArray());
        Pembayaran pembayaran = new Pembayaran();
        pembayaran.generateKodePembayaran();
        String kp = pembayaran.getKodepembayaran();        
        txtkp.setText(kp);
        
        Diskon dsk = new DiskonMember();
        
        if(cmb_langganan.getSelectedIndex()==0)
        {
            Pembayaran pb = new Pembayaran();
            pb.dataPembayaran(Integer.parseInt(txtpembayaran.getText()));
            pb.dataHarga(Integer.parseInt(txthargabarang.getText()));
            pb.setkodepembayaran(txtkp.getText());
            memopembayaran.setText(" ");
            memopembayaran.append("TOTAL PEMBAYARAN \n");
            memopembayaran.append("=================\n");
            memopembayaran.append("TOTAL BIAYA = " + pb.cetakHarga()+ "\n");
            memopembayaran.append("DISKON = " + Double.toString(pb.diskon())+"\n");
            memopembayaran.append("PEMBAYARAN SEBESAR = " + pb.cetakPembayaran() + "\n");
            memopembayaran.append("KEMBALIAN = " + pb.cetakTotal()  + "\n");
            memopembayaran.append("=================\n");
        } else if (cmb_langganan.getSelectedIndex()==1) {
             Pembayaran pbl = new Pembayaran ();
             pbl.dataPembayaran(Integer.parseInt(txtpembayaran.getText()));
             pbl.dataHarga(Integer.parseInt(txthargabarang.getText()));
             pbl.setkodepembayaran(txtkp.getText());
             memopembayaran.setText(" ");
             memopembayaran.append("TOTAL PEMBAYARAN \n");
             memopembayaran.append("=================\n");
             memopembayaran.append("TOTAL BIAYA = " + pbl.cetakHarga()+ "\n");
             memopembayaran.append("DISKON = " + Double.toString(pbl.hitungLangganan(0.1))+"\n");
             memopembayaran.append("PEMBAYARAN SEBESAR = " + pbl.cetakPembayaran() + "\n");
             memopembayaran.append("KEMBALIAN = " + pbl.cetakTotal()  + "\n");
             memopembayaran.append("=================\n");
        } else {
             dsk = new DiskonMember();
             DiskonMember dm = (DiskonMember) dsk;
             dm.dataPembayaran(Integer.parseInt(txtpembayaran.getText()));
             dm.dataHarga(Integer.parseInt(txthargabarang.getText()));
             dm.setkodepembayaran(txtkp.getText());
             memopembayaran.setText(" ");
             memopembayaran.append("TOTAL PEMBAYARAN \n");
             memopembayaran.append("=================\n");
             memopembayaran.append("TOTAL BIAYA = " + dsk.cetakHarga()+ "\n");
             memopembayaran.append("DISKON = " + Double.toString(dsk.diskon())+"\n");
             memopembayaran.append("PEMBAYARAN SEBESAR = " + dsk.cetakPembayaran() + "\n");
             memopembayaran.append("KEMBALIAN = " + dsk.cetakTotal()  + "\n");
             memopembayaran.append("=================\n");
        }
        

        //Pembayaran bayar = new Pembayaran();
        //bayar.dataPembayaran(Integer.parseInt(txtpembayaran.getText()));
        //bayar.dataHarga(Integer.parseInt(txthargabarang.getText()));
        //bayar.setkodepembayaran(txtkp.getText());
        //memopembayaran.append("Kode Pembayaran = " +bayar.);
        
    }//GEN-LAST:event_btnbayarActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void txtkpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkpActionPerformed

    private void cmb_langgananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_langgananActionPerformed
        // TODO add your handling code here
    }//GEN-LAST:event_cmb_langgananActionPerformed

    private void btn_battalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_battalActionPerformed
        // TODO add your handling code here:
        clear ();
    }//GEN-LAST:event_btn_battalActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dataModel = (DefaultTableModel) tabel_data_pembayaran.getModel();
        int rowCount = dataModel.getRowCount();
        while (rowCount>0){
            dataModel.removeRow(rowCount - 1);
            rowCount= dataModel.getRowCount();
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Pembayaran().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_battal;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JToggleButton btnbayar;
    private javax.swing.JToggleButton btnclose;
    private javax.swing.JComboBox<String> cmb_langganan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea memopembayaran;
    private javax.swing.JTable tabel_data_pembayaran;
    private javax.swing.JTextField txthargabarang;
    private static javax.swing.JTextField txtkp;
    private javax.swing.JTextField txtpembayaran;
    // End of variables declaration//GEN-END:variables
}
